packages:
  - apps/*
  - packages/*

catalog:
  prettier: 3.9.6
  typescript: 7.0.2
  vitest: 4.1.10
  zod: 4.4.3

disallowWorkspaceCycles: true
engineStrict: true
linkWorkspacePackages: false
nodeVersion: 24.18.0
pmOnFail: error
savePrefix: ""
saveWorkspaceProtocol: rolling
sharedWorkspaceLockfile: true
