export function cloneFixture<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export const generationInputSnapshotFixture = {
  snapshot_version: "input-v1",
  product_date: "2026-07-20",
  result_version: "daily-v1",
  checkin: {
    revision: 1,
    mood: "STEADY",
    energy: "LOW",
    sleep: "OKAY",
  },
  profile: {
    revision: 2,
    expression_style: "BALANCED",
  },
  relationship: {
    stage: "NEWLY_MET",
    encounter_day_count: 2,
  },
  permitted_context: [],
};

export const publishedDailyResultFixture = {
  contract: "daily-content",
  schema_version: "1.0.0",
  identity: {
    result_id: "dr_example_20260720",
    user_ref: "user_example",
    product_date: "2026-07-20",
    result_version: "daily-v1",
    generated_at: "2026-07-20T08:05:00Z",
  },
  input_snapshot_ref: "input_example_v1",
  facts: {
    overall: {
      score: 58,
      band: "STEADY",
      label_token: "KEEP_IT_STEADY",
    },
    dimensions: [
      { id: "pace", score: 54, band: "STEADY", label_token: "KEEP_IT_STEADY" },
      { id: "action", score: 43, band: "LOW", label_token: "TAKE_IT_GENTLY" },
      {
        id: "connection",
        score: 63,
        band: "STEADY",
        label_token: "KEEP_IT_STEADY",
      },
      {
        id: "resources",
        score: 57,
        band: "STEADY",
        label_token: "KEEP_IT_STEADY",
      },
      { id: "recovery", score: 72, band: "HIGH", label_token: "ROOM_TO_MOVE" },
    ],
    focus_dimension_id: "action",
    supporting_dimension_id: "recovery",
    care_dimension_id: "action",
    display_order: ["action", "pace", "connection", "resources", "recovery"],
    explanation_basis: [
      { type: "CHECKIN_SIGNAL", code: "SELF_REPORTED_ENERGY_LOW" },
      { type: "DIMENSION_SIGNAL", code: "ACTION_NEEDS_LIGHTER_START" },
    ],
    action_candidates: [
      {
        action_id: "act_reduce_switching",
        kind: "REDUCE_SWITCHING",
        target_scope: "ONE_TASK",
        effort: "VERY_LIGHT",
        timebox_minutes: 10,
        constraint_token: "NO_MULTITASKING",
      },
      {
        action_id: "act_prepare_one_step",
        kind: "PREPARE_ONE_STEP",
        target_scope: "ONE_STEP",
        effort: "LIGHT",
        timebox_minutes: 15,
      },
    ],
    selected_action_id: "act_reduce_switching",
    optional_task_plan: {
      task_id: "task_close_one_background",
      kind: "REDUCE_SWITCHING",
      effort: "VERY_LIGHT",
    },
    ritual_facts: [
      { ritual_id: "ritual_color_sage", kind: "COLOR", value: "SAGE_GREEN" },
      { ritual_id: "ritual_number_4", kind: "NUMBER", value: 4 },
    ],
  },
  expression: {
    greeting: "早上好，我们先把今天放稳一点。",
    state_response: "你今天的精力不算满，少一点切换会比硬撑更省力。",
    overall_summary: "今天适合稳住节奏，再推进一小步。",
    core_tip: "先保护注意力，再决定今天真正要推进的那一件事。",
    explanation_paragraphs: [
      "今天的行动余量偏轻，但恢复留白相对充足。与其同时开启很多事情，不如把注意力留给一个清楚的小目标。",
      "沟通和资源安排保持平稳，提前确认一次重点，就能减少临场切换。",
    ],
    dimension_explanations: {
      pace: "节奏适合保持稳定，不必突然加速。",
      action: "行动先从最小的一步开始，别同时推进。",
      connection: "沟通可以多确认一次，减少彼此猜测。",
      resources: "时间和注意力够用，但需要先排顺序。",
      recovery: "今天有一点留白余量，可以用来恢复。",
    },
    primary_action: {
      action_id: "act_reduce_switching",
      instruction: "关掉一个不必要的后台，只推进眼前最重要的一件事。",
      rationale: "减少切换，比勉强提高速度更有效。",
      constraint_label: "先做十分钟",
    },
    optional_task: {
      task_id: "task_close_one_background",
      instruction: "现在关闭一个会分散注意力的页面。",
    },
    ritual_notes: {
      ritual_color_sage: "把鼠尾草绿当作今天的小小仪式感。",
      ritual_number_4: "数字 4 只是一点轻松的娱乐参考。",
    },
    closing: "今天先做好这一件就够了。",
  },
  source_dependencies: [],
  privacy_fallbacks: {},
  provenance: {
    input_snapshot_version: "input-v1",
    rule_version: "rules-example-v1",
    algorithm_version: "algorithm-example-v1",
    generation_mode: "PRIMARY_AI",
    personalization_level: "FULL",
    prompt_version: "prompt-example-v1",
    provider: "internal-example",
    model: "model-example",
    safety_policy_version: "safety-example-v1",
  },
  validation: {
    status: "PASSED",
    validated_at: "2026-07-20T08:05:00Z",
  },
};

export const clientDailyContentViewFixture = {
  contract: "daily-content-view",
  schema_version: "1.0.0",
  result_id: "dr_example_20260720",
  product_date: "2026-07-20",
  result_version: "daily-v1",
  generated_at: "2026-07-20T08:05:00Z",
  content_label: "娱乐与行动参考",
  greeting: "早上好，我们先把今天放稳一点。",
  state_response: "你今天的精力不算满，少一点切换会比硬撑更省力。",
  overall: {
    band: "STEADY",
    band_label: "适合稳住",
    summary: "今天适合稳住节奏，再推进一小步。",
  },
  focus_dimension_id: "action",
  dimensions: [
    {
      id: "action",
      label: "行动推进",
      band: "LOW",
      band_label: "适合放轻",
      explanation: "行动先从最小的一步开始，别同时推进。",
      is_focus: true,
    },
    {
      id: "pace",
      label: "今日节奏",
      band: "STEADY",
      band_label: "适合稳住",
      explanation: "节奏适合保持稳定，不必突然加速。",
      is_focus: false,
    },
    {
      id: "connection",
      label: "沟通连接",
      band: "STEADY",
      band_label: "适合稳住",
      explanation: "沟通可以多确认一次，减少彼此猜测。",
      is_focus: false,
    },
    {
      id: "resources",
      label: "资源安排",
      band: "STEADY",
      band_label: "适合稳住",
      explanation: "时间和注意力够用，但需要先排顺序。",
      is_focus: false,
    },
    {
      id: "recovery",
      label: "恢复留白",
      band: "HIGH",
      band_label: "余量较多",
      explanation: "今天有一点留白余量，可以用来恢复。",
      is_focus: false,
    },
  ],
  core_tip: "先保护注意力，再决定今天真正要推进的那一件事。",
  explanation_paragraphs: [
    "今天的行动余量偏轻，但恢复留白相对充足。与其同时开启很多事情，不如把注意力留给一个清楚的小目标。",
    "沟通和资源安排保持平稳，提前确认一次重点，就能减少临场切换。",
  ],
  primary_action: {
    action_id: "act_reduce_switching",
    instruction: "关掉一个不必要的后台，只推进眼前最重要的一件事。",
    rationale: "减少切换，比勉强提高速度更有效。",
    constraint_label: "先做十分钟",
  },
  optional_task: {
    task_id: "task_close_one_background",
    instruction: "现在关闭一个会分散注意力的页面。",
  },
  rituals: [
    {
      kind: "COLOR",
      display_value: "鼠尾草绿",
      note: "把鼠尾草绿当作今天的小小仪式感。",
    },
    {
      kind: "NUMBER",
      display_value: "4",
      note: "数字 4 只是一点轻松的娱乐参考。",
    },
  ],
  closing: "今天先做好这一件就够了。",
  personalization_notice: "NONE",
};

export const eveningSubmissionFixture = {
  contract: "evening-reflection-submission",
  schema_version: "1.0.0",
  submission_id: "ers_example_001",
  product_date: "2026-07-20",
  expected_feedback_revision: 0,
  expected_helpfulness_revision: 0,
  overall_feeling: "STEADY",
  helpfulness_rating: "HELPFUL",
  task_patch: {
    task_id: "task_close_one_background",
    expected_revision: 1,
    status: "COMPLETED",
  },
  note_patch: {
    operation: "SET",
    value: "下午把最难的一件事拆小后，心里轻了一点。",
  },
  client_context: {
    entry_source: "TODAY_EVENING_CARD",
    view_schema_version: "1.0.0",
  },
};

export const eveningRecordFixture = {
  contract: "evening-feedback",
  schema_version: "1.0.0",
  feedback_id: "ef_example_20260720",
  user_ref: "user_example",
  product_date: "2026-07-20",
  revision: 1,
  overall_feeling: "STEADY",
  note: "下午把最难的一件事拆小后，心里轻了一点。",
  first_submitted_at: "2026-07-20T12:10:00Z",
  updated_at: "2026-07-20T12:10:00Z",
  source_submission_id: "ers_example_001",
  safety_policy_version: "safety-example-v1",
};

export const clientEveningViewFixture = {
  contract: "evening-feedback-view",
  schema_version: "1.0.0",
  product_date: "2026-07-20",
  availability: "EDITABLE_SUBMITTED",
  write_window: "OPEN",
  feedback: {
    revision: 1,
    overall_feeling: "STEADY",
    note: "下午把最难的一件事拆小后，心里轻了一点。",
    first_submitted_at: "2026-07-20T12:10:00Z",
    updated_at: "2026-07-20T12:10:00Z",
  },
  helpfulness: { revision: 1, rating: "HELPFUL" },
  task: {
    task_id: "task_close_one_background",
    instruction: "现在关闭一个会分散注意力的页面。",
    revision: 2,
    status: "COMPLETED",
  },
  options: {
    overall_feeling: [
      "VERY_HEAVY",
      "SOMEWHAT_HEAVY",
      "STEADY",
      "PRETTY_GOOD",
      "LIGHT",
      "UNSURE",
    ],
    helpfulness: ["HELPFUL", "NEUTRAL", "NOT_HELPFUL", "NOT_USED"],
    task_status: ["UNMARKED", "INTERESTED", "COMPLETED", "SKIPPED"],
  },
  note_max_characters: 80,
  primary_action: "SAVE_CHANGES",
  completion_message: "今天先到这里，这些记录已经留下了。",
};

export const weeklySourceSnapshotFixture = {
  contract: "weekly-source-snapshot",
  schema_version: "1.0.0",
  window_id: "ww_example_20260720",
  window_start_date: "2026-07-14",
  window_end_date: "2026-07-20",
  window_rule_version: "window-v1",
  days: [
    {
      product_date: "2026-07-14",
      source_state: "RECORDED",
      checkin: {
        source_ref: "checkin_example_14",
        revision: 1,
        mood: "STEADY",
        energy: "LOW",
        sleep: "OKAY",
      },
      light: { source_ref: "light_example_14", is_lit: true },
      helpfulness: {
        source_ref: "help_example_14",
        revision: 1,
        rating: "HELPFUL",
        action_kind: "REDUCE_SWITCHING",
      },
      task: {
        source_ref: "task_example_14",
        revision: 2,
        status: "COMPLETED",
      },
    },
    { product_date: "2026-07-15", source_state: "MISSING" },
    { product_date: "2026-07-16", source_state: "MISSING" },
    { product_date: "2026-07-17", source_state: "MISSING" },
    { product_date: "2026-07-18", source_state: "MISSING" },
    { product_date: "2026-07-19", source_state: "MISSING" },
    { product_date: "2026-07-20", source_state: "MISSING" },
  ],
  source_fingerprint: "source-fingerprint-example",
};

export const weeklyExpressionFixture = {
  title: "这七天，先看见真实留下的部分",
  opening: {
    text: "这七天里，你留下了 5 天真实状态，也点亮了其中 4 天。缺失的日期会继续留空。",
    fact_refs: ["fact.coverage.real_days", "fact.light.count"],
  },
  observations: [
    {
      text: "基于 4 次可用的精力记录，后几次相对偏低；这只是这段时间的记录方向，不代表固定状态。",
      fact_refs: ["fact.energy.direction", "fact.energy.observed_count"],
    },
    {
      text: "你有 3 天留下了晚间回看，这三次的整体感受大致相近；样本不多，先把它看作一段记录。",
      fact_refs: ["fact.feedback.count", "fact.evening.direction"],
    },
  ],
  helpful_pattern: {
    text: "目前更有信号的是先减少切换，但样本还不多，不必把它当成固定答案。",
    fact_refs: ["fact.helpfulness.top_action_kind"],
  },
  next_week: {
    text: "下一周可以轻轻留意：一天里什么时候更容易觉得有余量，不需要每天都记。",
    fact_refs: ["plan.notice_energy_timing"],
  },
  closing: {
    text: "已经留下的这些，就足够成为下一次回看的起点。",
    fact_refs: ["fact.coverage.level"],
  },
};

export const weeklyClientDays = [
  {
    product_date: "2026-07-14",
    state: "RECORDED",
    morning: { mood: "STEADY", energy: "LOW", sleep: "OKAY" },
    evening: { overall_feeling: "STEADY" },
    is_lit: true,
    helpfulness: "HELPFUL",
    task_status: "COMPLETED",
  },
  { product_date: "2026-07-15", state: "MISSING", is_lit: false },
  {
    product_date: "2026-07-16",
    state: "RECORDED",
    morning: { mood: "GOOD", energy: "STEADY", sleep: "GOOD" },
    is_lit: true,
    helpfulness: "UNRATED",
    task_status: "UNMARKED",
  },
  {
    product_date: "2026-07-17",
    state: "RECORDED",
    morning: { mood: "STEADY", energy: "LOW", sleep: "LOW" },
    evening: { overall_feeling: "SOMEWHAT_HEAVY" },
    is_lit: true,
    helpfulness: "HELPFUL",
    task_status: "SKIPPED",
  },
  { product_date: "2026-07-18", state: "MISSING", is_lit: false },
  {
    product_date: "2026-07-19",
    state: "RECORDED",
    morning: { mood: "LOW", energy: "EMPTY", sleep: "LOW" },
    is_lit: true,
    helpfulness: "NOT_USED",
    task_status: "INTERESTED",
  },
  {
    product_date: "2026-07-20",
    state: "RECORDED",
    morning: { mood: "UNSURE", energy: "LOW", sleep: "OKAY" },
    evening: { overall_feeling: "STEADY" },
    is_lit: false,
    helpfulness: "NEUTRAL",
    task_status: "UNMARKED",
  },
];

export const weeklyAggregateFactsFixture = {
  contract: "weekly-aggregate-facts",
  schema_version: "1.0.0",
  window_id: "ww_example_20260720",
  window_start_date: "2026-07-14",
  window_end_date: "2026-07-20",
  coverage: {
    window_day_count: 7,
    real_state_day_count: 5,
    checkin_day_count: 5,
    evening_feedback_day_count: 3,
    lit_day_count: 4,
    missing_dates: ["2026-07-15", "2026-07-18"],
    coverage_level: "PARTIAL",
  },
  day_slots: weeklyClientDays.map((day) => ({
    ...day,
    helpfulness: day.helpfulness ?? "UNRATED",
    ...(day.helpfulness === "HELPFUL"
      ? { helpful_action_kind: "REDUCE_SWITCHING" }
      : {}),
  })),
  state_metrics: [
    {
      metric_id: "MORNING_MOOD",
      observed_count: 4,
      unsure_count: 1,
      missing_count: 2,
      distribution: { VERY_LOW: 0, LOW: 1, STEADY: 2, GOOD: 1, LIGHT: 0 },
      mode_value: "STEADY",
      mode_count: 2,
      direction: "LOWER_LATE",
      direction_basis_count: 4,
    },
    {
      metric_id: "MORNING_ENERGY",
      observed_count: 5,
      unsure_count: 0,
      missing_count: 2,
      distribution: { EMPTY: 1, LOW: 3, STEADY: 1, HIGH: 0, FULL: 0 },
      mode_value: "LOW",
      mode_count: 3,
      direction: "LOWER_LATE",
      direction_basis_count: 5,
    },
    {
      metric_id: "MORNING_SLEEP",
      observed_count: 5,
      unsure_count: 0,
      missing_count: 2,
      distribution: { POOR: 0, LOW: 2, OKAY: 2, GOOD: 1 },
      direction: "VARIABLE",
      direction_basis_count: 5,
    },
    {
      metric_id: "EVENING_OVERALL",
      observed_count: 3,
      unsure_count: 0,
      missing_count: 4,
      distribution: {
        VERY_HEAVY: 0,
        SOMEWHAT_HEAVY: 1,
        STEADY: 2,
        PRETTY_GOOD: 0,
        LIGHT: 0,
      },
      mode_value: "STEADY",
      mode_count: 2,
      direction: "SIMILAR",
      direction_basis_count: 3,
    },
  ],
  light_facts: { lit_day_count: 4 },
  feedback_facts: { evening_feedback_day_count: 3 },
  helpfulness_facts: {
    rated_day_count: 4,
    helpful_count: 2,
    neutral_count: 1,
    not_helpful_count: 0,
    not_used_count: 1,
    unrated_day_count: 3,
    helpful_action_kind_counts: { REDUCE_SWITCHING: 2 },
    top_helpful_action_kind: "REDUCE_SWITCHING",
  },
  task_facts: {
    task_offered_day_count: 5,
    completed_count: 1,
    skipped_count: 1,
    interested_count: 1,
    unmarked_count: 2,
  },
  approved_fact_catalog: [
    "fact.coverage.real_days",
    "fact.light.count",
    "fact.energy.direction",
    "fact.energy.observed_count",
    "fact.feedback.count",
    "fact.evening.direction",
    "fact.helpfulness.top_action_kind",
    "plan.notice_energy_timing",
    "fact.coverage.level",
    "fact.coverage.disclosure",
  ],
  source_fingerprint: "source-fingerprint-example",
  aggregate_version: "weekly-aggregate-v1",
};

export const weeklyExpressionPlanFixture = {
  coverage_level: "PARTIAL",
  approved_fact_ids: weeklyAggregateFactsFixture.approved_fact_catalog,
  headline_fact_id: "fact.coverage.real_days",
  observation_fact_ids: ["fact.energy.direction", "fact.evening.direction"],
  helpful_pattern_fact_id: "fact.helpfulness.top_action_kind",
  next_observation_plan: "NOTICE_ENERGY_TIMING",
  next_observation_fact_id: "plan.notice_energy_timing",
  coverage_fact_id: "fact.coverage.level",
  source_disclosure_fact_id: "fact.coverage.disclosure",
};

export const publishedWeeklySummaryFixture = {
  contract: "weekly-summary",
  schema_version: "1.0.0",
  summary_id: "ws_example_revision_1",
  summary_revision: 1,
  window_id: "ww_example_20260720",
  window_start_date: "2026-07-14",
  window_end_date: "2026-07-20",
  source_fingerprint: "source-fingerprint-example",
  aggregate_facts_ref: "weekly-aggregate-example",
  expression_version: "weekly-expression-v1",
  expression_plan: weeklyExpressionPlanFixture,
  expression: weeklyExpressionFixture,
  source_dependencies: [],
  privacy_fallbacks: {},
  provenance: {
    generation_mode: "PRIMARY_AI",
    personalization_level: "FULL",
    prompt_version: "weekly-prompt-v1",
    provider: "internal-example",
    model: "model-example",
    safety_policy_version: "safety-example-v1",
  },
  validation: { status: "PASSED", validated_at: "2026-07-20T12:20:00Z" },
  published_at: "2026-07-20T12:20:00Z",
};

export const clientWeeklySummaryViewFixture = {
  contract: "weekly-summary-view",
  schema_version: "1.0.0",
  window_id: "ww_example_20260720",
  window_start_date: "2026-07-14",
  window_end_date: "2026-07-20",
  projection_version: "weekly-view-v1",
  coverage: {
    level: "PARTIAL",
    window_day_count: 7,
    real_state_day_count: 5,
    checkin_day_count: 5,
    evening_feedback_day_count: 3,
    lit_day_count: 4,
    missing_dates: ["2026-07-15", "2026-07-18"],
  },
  days: weeklyClientDays,
  metrics: [
    {
      id: "MORNING_MOOD",
      observed_count: 4,
      unsure_count: 1,
      missing_count: 2,
      direction: "LOWER_LATE",
      direction_label: "后几次记录相对偏低",
    },
    {
      id: "MORNING_ENERGY",
      observed_count: 5,
      unsure_count: 0,
      missing_count: 2,
      direction: "LOWER_LATE",
      direction_label: "后几次记录相对偏低",
    },
    {
      id: "MORNING_SLEEP",
      observed_count: 5,
      unsure_count: 0,
      missing_count: 2,
      direction: "VARIABLE",
      direction_label: "这几次有些起伏",
    },
    {
      id: "EVENING_OVERALL",
      observed_count: 3,
      unsure_count: 0,
      missing_count: 4,
      direction: "SIMILAR",
      direction_label: "这几次大致相近",
    },
  ],
  activity: {
    lit_day_count: 4,
    helpfulness: {
      rated_day_count: 4,
      helpful_count: 2,
      neutral_count: 1,
      not_helpful_count: 0,
      not_used_count: 1,
      unrated_day_count: 3,
      top_helpful_action_kind: "REDUCE_SWITCHING",
    },
    tasks: {
      task_offered_day_count: 5,
      completed_count: 1,
      skipped_count: 1,
      interested_count: 1,
      unmarked_count: 2,
    },
  },
  summary: {
    summary_id: "ws_example_revision_1",
    revision: 1,
    kind: "PARTIAL_REVIEW",
    title: "这七天，先看见真实留下的部分",
    paragraphs: [
      "这七天里，你留下了 5 天真实状态，也点亮了其中 4 天。缺失的日期会继续留空。",
      "基于 4 次可用的情绪记录和 5 次精力记录，后几次相对偏低；这只是这段时间的记录方向，不代表固定状态。",
      "你有两次觉得减少切换的建议有帮助。下一周可以轻轻留意一天里什么时候更容易觉得有余量，不需要每天都记。",
      "已经留下的这些，就足够成为下一次回看的起点。",
    ],
  },
  summary_status: "AVAILABLE",
  data_disclosure: "基于 5 天真实状态；2 个日期没有记录，未做推断或补齐。",
};
