services:
  host-ingress:
    networks:
      host_ingress:
    ports:
      - 127.0.0.1:${DAILYENERGY_API_HOST_PORT:-3300}:13000
      - 127.0.0.1:${DAILYENERGY_ADMIN_HOST_PORT:-3301}:13001

networks:
  host_ingress:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
